sudo: required
services:
  - docker

before_install:
  - docker build -t docker-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true docker-complex yarn run test -- --coverage

language: generic

after_success:
  - docker build -t leearnold/dc-client ./client
  - docker build -t leearnold/dc-nginx ./nginx
  - docker build -t leearnold/dc-server ./server
  - docker build -t leearnold/dc-worker ./worker
  #log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_NAME" --password-stdin
  - docker push leearnold/dc-client
  - docker push leearnold/dc-nginx
  - docker push leearnold/dc-server
  - docker push leearnold/dc-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-complex"
  env: "Dockercomplex-env"
  bucket_name: "elasticbeanstalk-us-east-2-114682673195"
  bucket_path: "docker-complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY